config/routes.rb
Rails.application.routes.draw do
  root "documents#index"

  resources :documents do
    resources :fragments
  end

  get '/documents/:id/markdown', to: "documents#markdown", as: 'document_markdown'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :fragments, -> { order(position: :asc) }, dependent: :destroy
end

app/models/fragment.rb
class Fragment < ApplicationRecord
  belongs_to :document
  acts_as_list scope: :document
  has_one_attached :image

  attr_accessor :saved

  def to_md
    Wysiwyg::Markdown::MAPPINGS[element] % {data: data, meta: meta}
  end

  def render
    Wysiwyg::Markdown::Renderer.md_to_html(to_md)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy markdown]

  # GET /documents or /documents.json
  def index
    @groups = Document.order(note: :asc, updated_at: :desc).all.group_by(&:note)
  end

  # GET /documents/1 or /documents/1.json
  def show
    @fragments = @document.fragments.order(position: :asc)
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        @document.fragments.build(element: "p", data: "edit me").save
        format.html { redirect_to @document, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def markdown
    fragments = @document.fragments.order(position: :asc)
    source = fragments.map(&:to_md).join("\n\n")
    formatter = Rouge::Formatters::HTML.new
    lexer = Rouge::Lexers::Markdown.new
    @markdown = formatter.format(lexer.lex(source)).html_safe
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:title, :note)
    end
end

app/controllers/fragments_controller.rb
class FragmentsController < ApplicationController
  before_action :set_document
  before_action :set_fragment, only: [:update, :destroy]

  def create
    @fragment = @document.fragments.build(fragment_params)
    @fragment.save

    redirect_to(document_path(@document))
  end

  def update
    @fragment.update(fragment_params)
    @fragment.saved = true

    render @fragment
  end

  def destroy
    @fragment.destroy
    redirect_to(document_path(@document))
  end

  private

  def set_fragment
    @fragment = @document.fragments.find(params[:id])
  end

  def set_document
    @document = Document.find(params[:document_id])
  end

  def fragment_params
    params.require(:fragment).permit(:element, :data, :meta, :position, :image)
  end
end

app/controllers/menus_controller.rb
# frozen_string_literal: true

class MenusController < ApplicationController
  def add_fragment
  end

  def change_fragment
  end

  def format_selection
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/view_helper.rb
# frozen_string_literal: true

module ViewHelper
  def page(*args, **kwargs, &block)
    render PageComponent.new(*args, **kwargs), &block
  end
end

app/views/documents/_document.html.erb
  <%= tag.div class: "box is-flex is-flex-direction-row is-align-items-center" do %>
    <%= link_to document, id: dom_id(document) do %>
      <div class="is-6"><%= document.title %></div>
    <% end %>
    <div class="is-flex-grow-1 has-text-right">
      <%= link_to "Change Metadata", edit_document_path(document), class: "button is-small is-link is-light" %>
      <%= link_to "Edit Document", document_path(document), class: "button is-small is-warning is-light" %>
    </div>
  <% end %>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label" %>
    <div class="control">
      <%= form.text_field :title, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :note, "Document group",  class: "label" %>
    <div class="control">
      <%= form.text_field :note, class: "input" %>
    </div>
  </div>

  <div class="actions mt-5 has-text-right">
    <% if document.persisted? %>
      <%= button_to "Delete", document_path(document), method: :delete, class: "button is-danger" %>
    <% end %>
    <%= form.submit nil, class: "button is-link" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<%= page(title: "Edit Document") do |p| %>

 <% p.breadcrumbs do |breadcrumbs| %>
   <% breadcrumbs.breadcrumb(label: "Documents", href: documents_path) %>
   <% breadcrumbs.breadcrumb(label: @document.title, href: document_path(@document)) %>
   <% breadcrumbs.breadcrumb(label: "Edit", href: edit_document_path(@document), active: true) %>
 <% end %>

 <% p.actions do %>
  <%= link_to documents_path, class: "button with-icon is-primary" do %>
     <i class="gg-arrow-left"></i>
     <span>Back to documents</span>
   <% end %>
 <% end %>

  <div class="box mt-5 p-5">
    <%= render "form", document: @document %>
  </div>

  <div class="mt-3 p-2 has-text-right"></div>

<% end %>

app/views/documents/index.html.erb
 <%= page(title: "Your Documents") do |p| %>

  <% p.breadcrumbs do |breadcrumbs| %>
    <% breadcrumbs.breadcrumb(label: "Documents", href: documents_path, active: true) %>
  <% end %>

  <% p.actions do %>
    <%= link_to new_document_path, class: "button with-icon is-primary" do %>
      <i class="gg-math-plus"></i>
      <span>Add document</span>
    <% end %>
  <% end %>

  <% @groups.each do |name, group| %>
    <div class="document-group">
      <h3 class="title is-5"><%= name %></h3>
      <%= render group %>
    </div>
  <% end %>

 <% end %>

app/views/documents/markdown.html.erb
<%= page(title: @document.title) do |p| %>

  <% p.breadcrumbs do |breadcrumbs| %>
    <% breadcrumbs.breadcrumb(label: "Documents", href: documents_path) %>
    <% breadcrumbs.breadcrumb(label: @document.title, href: document_path(@document)) %>
    <% breadcrumbs.breadcrumb(label: "Markdown Preview", href: "#", active: true) %>
  <% end %>

  <% p.actions do %>
    <%= link_to document_path(@document), class: "button with-icon is-primary" do %>
      <i class="gg-arrow-left"></i>
      <span>Back to Document</span>
    <% end %>
  <% end %>

  <div class="markdown-preview" data-controller="clipboard">
    <button class="button is-small" data-action="click->clipboard#copy"><i class="gg-clipboard"></i></button>
    <pre><code data-clipboard-target="source"><%= @markdown %></code></pre>
  </div>

<% end %>

app/views/documents/new.html.erb
<%= page(title: "New Document") do |p| %>

 <% p.breadcrumbs do |breadcrumbs| %>
   <% breadcrumbs.breadcrumb(label: "Documents", href: documents_path) %>
   <% breadcrumbs.breadcrumb(label: "New", href: "#", active: true) %>
 <% end %>

 <% p.actions do %>
  <%= link_to documents_path, class: "button with-icon is-primary" do %>
     <i class="gg-arrow-left"></i>
     <span>Back to documents</span>
   <% end %>
 <% end %>

  <div class="box mt-5 p-5">
    <%= render "form", document: @document %>
  </div>

  <div class="mt-3 p-2 has-text-right"></div>

<% end %>

app/views/documents/show.html.erb
<%= page(title: @document.title) do |p| %>

 <% p.breadcrumbs do |breadcrumbs| %>
   <% breadcrumbs.breadcrumb(label: "Documents", href: documents_path) %>
   <% breadcrumbs.breadcrumb(label: @document.title, href: document_path(@document), active: true) %>
 <% end %>

 <% p.actions do %>
   <%= link_to document_markdown_path(@document), class: "button with-icon is-primary" do %>
     <i class="gg-attribution"></i>
     <span>Render Markdown</span>
   <% end %>
 <% end %>

  <div class="document">

    <%= turbo_frame_tag :fragments do %>
      <div class="fragments-container" data-controller="sortable">
        <%= render @fragments %>
      </div>
    <% end %>

  </div>

<% end %>

app/views/fragments/_fragment.html.erb
<div class="draggable">
  <%= turbo_frame_tag dom_id(fragment) do %>

    <div
      class="fragment-wrapper <%= fragment.element %> <%= fragment.saved ? 'saved' : '' %>"
      data-controller="editable change-fragment"
    >
      <div class="fragment-button-container">

        <button
          class="button is-small is-link is-round"
          data-action="click->change-fragment#showMenu"
        >
          <i class="gg-chevron-down"></i>
        </button>
      </div>

      <div class="fragment-container">
        <div
          class="fragment <%= fragment.element %>"
          data-editable-target="editable"
          data-action="
            click->editable#click
            blur->editable#blur
            keydown->editable#keyDown
            paste->editable#paste
            mouseup->editable#mouseUp
            mousedown->editable#mouseDown"
        >
          <%= fragment.render %>
        </div>

        <%= form_with(model: [@document, fragment]) do |form| %>
          <%= form.text_area(:data, hidden: true) %>
          <%= form.text_field(:element, hidden: true) %>
          <%= form.text_field(:meta, hidden: true) %>
          <%= form.text_field(:position, hidden: true) %>

          <%= form.submit("Save", hidden: true) %>
        <% end %>

        <%= button_to(
          "Delete",
          document_fragment_path(@document, fragment),
          method: :delete,
          data: {
            turbo_method: :delete,
            turbo_frame: :fragments
          },
          hidden: true
        ) %>
      </div>
    </div>

  <% end %>

  <%= render "fragments/new", fragment: fragment %>
</div>

app/views/fragments/_new.html.erb
<div class="add-fragment" data-controller="add-fragment">
  <div class="add-fragment-button-container">
    <%= form_with(
      model: [@document, @document.fragments.build(
        element: "p",
        data: "edit me",
        position: (fragment.position + 1))]) do |form| %>
      <%= form.text_field :data, hidden: true %>
      <%= form.text_field :element, hidden: true %>
      <%= form.text_field :meta, hidden: true %>
      <%= form.text_field :position, hidden: true %>
      <%= form.submit("Create", hidden: true) %>
      <button
        class="button is-link is-round is-small"
        data-action="click->add-fragment#showMenu">
        <i class="gg-math-plus"></i>
      </button>
    <% end %>
  </div>
  <hr class="add-fragment-indicator"></hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <style><%= Rouge::Themes::MonokaiSublime.render(scope: 'pre') %></style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>